site_name: PhishLens-TR
site_url: https://redzeptech.github.io/phishlens-tr/
repo_url: https://github.com/redzeptech/phishlens-tr

theme:
  name: material
  language: tr

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true

nav:
  - Giriş: index.md
  - Kurulum: wiki/Kurulum.md
  - Yapilandirma: wiki/Yapilandirma.md
  - Ozellikler: wiki/Ozellikler.md
